### ISSUE TITLE
Comments and indentation are removed from `extenion.yaml` when generating an overview dashboard

### ISSUE THREAD

**Issue by vduseev** [dynatrace-extensions/dynatrace-extensions-copilot#100]
**Summary**
When an overview dashboard is generated, the `extension.yaml` is modified in such way that rearranges the file and removes any comments in there.

**Current vs. Expected Behavior**
* Current: comments are removed and the `extension.yaml` is regenerated.
* Expected: all comments and indentation stays as-is.

**Suggestion**
Would it make sense to not modify the `extension.yaml` when generating a dashboard? Or maybe to optionally (via a prompt) add a single line at the end of it.

**Comment by radu-stefan-dt** [comment]
This is coming from the current use of node's YAML parser. Wherever possible we use text/regex to replace/modify content in the yaml file. However, for generating alerts & the dashboard, we are parsing the yaml and then stringifying it which does not keep comments and indents everything by yaml standards (2 space).

**Comment by radu-stefan-dt** [comment]
Quick fix for this ticket:
* Use regex to identify the "alerts" and "dashboards" yaml block declaration
* Always insert the generated item at the first index of the list
