### ISSUE TITLE
Wait needed after Deleting Oldest Extension Version

### ISSUE THREAD

**Issue by damass** [dynatrace-extensions/dynatrace-extensions-copilot#22]
When going through the build flow, upload, activate flow, if you already have 10 versions it successfully deletes the oldest version without issue. However, I think there needs to be a sleep for a short period of time before attempting to upload/activate the newest built version again as it seems to take some time for the Cluster to delete the oldest version and register it can accept a new version. At least every time it's happened to me it fails (tried with v0.19.0) and I have to re-upload/activate again.

**Comment by radu-stefan-dt** [comment]
Thanks for raising this issue. I noticed that myself with Fast Mode. 
Either a wait time (albeit difficult to ballpark) or a check via the API for confirmation seems the way forward.

Workarounds currently:
- In standard mode: if the flow fails, run the Upload Extension command manually (no need to rebuild)
- In fast mode: Save the doc again to re-trigger
