### ISSUE TITLE
Feature - JMX v1 to v2 converter

### ISSUE THREAD

**Issue by dlopes7** [dynatrace-extensions/dynatrace-extensions-copilot#71]
**Summary**
We should be able to automatically generate the `extension.yaml` file corresponding to a JMX v1 extension `plugin.json` file

**Details**
A command pallet called `Dynatrace: Convert JMX v1 extension`

The user can choòse:

a) Local -> open dialog to browse to file, load file (zip or json)  -> do the magic
b) Remote -> use API, show quick pick, download zip -> do the magic

**Use Cases**
With JMX v2 feature coming soon, users will need a convenient way to convert existing extensions to the new format.

**Challenges**
Data visualization can be challenging, start only with metric metadata and jmx datasource

**Comment by radu-stefan-dt** [comment]
@dlopes7 - could you check that we merged everyhting related to this ticket? 
Or is work still being done? sorry, I lost track of the PRs a bit.
