### ISSUE TITLE
.gitignore as part of workspace initialization

### ISSUE THREAD

**Issue by radu-stefan-dt** [dynatrace-extensions/dynatrace-extensions-copilot#89]
**Summary**
We should create/update a `.gitignore` file as part of the Initialize Workspace command.

**Details**
A few things are unnecessary from a repository perspective:
- `.vscode` folder
- `config` folder
- `dist`  potentially ?

**Use Cases**
As a developer using a git-based repository I want my repos to be clean. Configuration files (coming soon) may unintentionally expose credentials or sensitive data, whereas vscode settings are unnecessary. Even the `dist` directory is not necessarily needed as it will gather a lot of versioned packages.

**Comment by airborn** [comment]
Please refer to https://github.com/github/gitignore for good templates of what is worth ignoring. For example, some parts of .vscode are considered worth keeping: https://github.com/github/gitignore/blob/4488915eec0b3a45b5c63ead28f286819c0917de/Global/VisualStudioCode.gitignore#L2-L6
