### ISSUE TITLE
Add support for WSL2 and dev containers

### ISSUE THREAD

**Issue by StijnBienkens** [dynatrace-extensions/dynatrace-extensions-copilot#97]
**Summary**
Please add support for using this extension inside WSL2 and Dev Containers (VS Code Remote Development).

**Current vs. Expected Behavior**
When the extension is installed remotely (for instance inside WSL2), it doesn't work and the following error is thrown:

> Error: ENOENT: no such file or directory, open '/home/<user>/.vscode-server/data/User/workspaceStorage/70afb1239f07f57b48e7d2d8a7978be9/workspace.json'
> 	at Object.openSync (node:fs:585:3)
> 	at readFileSync (node:fs:453:35)
> 	at dt (/home/<user>/.vscode-server/extensions/dynatraceplatformextensions.dt-ext-copilot-1.1.0/out/main.js:166:11855)
> 	at /home/<user>/.vscode-server/extensions/dynatraceplatformextensions.dt-ext-copilot-1.1.0/out/main.js:168:5221
> 	at D.d (/home/<user>/.vscode-server/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/workbench/api/node/extensionHostProcess.js:99:46171)
> 	at D.withProgress (/home/<user>/.vscode-server/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/workbench/api/node/extensionHostProcess.js:99:46014)
> 	at Object.withProgress (/home/<user>/.vscode-server/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/workbench/api/node/extensionHostProcess.js:115:34084)
> 	at Mg (/home/<user>/.vscode-server/extensions/dynatraceplatformextensions.dt-ext-copilot-1.1.0/out/main.js:168:4341)
> 	at /home/<user>/.vscode-server/extensions/dynatraceplatformextensions.dt-ext-copilot-1.1.0/out/main.js:810:4113
> 	at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 	at async m.h (/home/<user>/.vscode-server/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/workbench/api/node/extensionHostProcess.js:99:125789)

**Comment by radu-stefan-dt** [comment]
Added as part of v 1.2.1 which is on the VSCode Marketplace, but not yet here on GH. Just update the version as normal and then select to install it in your remote environment. The only env currently unsupported is Web (https://vscode.dev).
